version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=host.docker.internal   # for local DB or RDS
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=test

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend